### ISSUE TITLE
 Error code:  No GPU Compatible

### ISSUE THREAD

**Issue by panecho** [stereolabs/zed-tracking-viewer#10]
my computer equiped with ubuntu16.04, GT740, cuda8.0. error info as follow when i run ZED_Depth_Viewer.

     ZED (Init) >> Invalid GPU device id
     [ INFO] [1496395832.260695438]: Error code:  No GPU Compatible

so do run the zed.launch in zed_wrapper ros package.
I just want to get the left and right image at the same time ,any access?

**Comment by adujardin** [comment]
Hi,

You should get in touch with the support at support@stereolabs.com for this issue (since it's not related to this sample).

**Comment by manomitbal** [comment]
Hi @ZhengPan2014, 

You can resolve this issue by either running ZED_Depth_Viewer executable with a 'sudo' or set root permissions to your nvidia-uvm module. You can do this by typing the following commands in terminal:

mknod -m 660 /dev/nvidia-uvm c 249 0

sudo chgrp video /dev/nvidia-uvm

Good luck!
