### ISSUE TITLE
Eigen Exception

### ISSUE THREAD

**Issue by tweeter0830** [stereolabs/zed-tracking-viewer#3]
I tried running this example under Ubuntu 16.04 and got the following:

ZED SDK >> (Init) Best GPU Found : Quadro K4000 , ID : 0
ZED SDK >> (Init) Disparity mode has been set to PERFORMANCE
ZED SDK >> (Init) Creating ZED GPU mem...
ZED SDK >> (Init) Starting Self-Calibration in background... 
ZED SDK >> (Init) Done...
SUCCESS
ZED SDK >> (Tracking) Relocalization activated.
ZED Tracking Viewer: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ****"' failed.
fish: “./ZED\ Tracking\ Viewer” terminated by signal SIGABRT (Abort)

**Comment by adujardin** [comment]
Hi,
Could you try the latest commit I just added, please ? It should fix the issue

**Comment by tweeter0830** [comment]
fixed

**Comment by tweeter0830** [comment]
thanks!
