### ISSUE TITLE
Ubuntu 16.04 LTS, CUDA 8.0, SDK1.2 library linking issue

### ISSUE THREAD

**Issue by jinchenglee** [stereolabs/zed-tracking-viewer#9]
$ make VERBOSE=1
/usr/bin/cmake -H/home/vitob/git_repositories/zed-tracking-viewer -B/home/vitob/git_repositories/zed-tracking-viewer/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/vitob/git_repositories/zed-tracking-viewer/build/CMakeFiles /home/vitob/git_repositories/zed-tracking-viewer/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
make -f CMakeFiles/ZED_Tracking_Viewer.dir/build.make CMakeFiles/ZED_Tracking_Viewer.dir/depend
make[2]: Entering directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
cd /home/vitob/git_repositories/zed-tracking-viewer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/vitob/git_repositories/zed-tracking-viewer /home/vitob/git_repositories/zed-tracking-viewer /home/vitob/git_repositories/zed-tracking-viewer/build /home/vitob/git_repositories/zed-tracking-viewer/build /home/vitob/git_repositories/zed-tracking-viewer/build/CMakeFiles/ZED_Tracking_Viewer.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
make -f CMakeFiles/ZED_Tracking_Viewer.dir/build.make CMakeFiles/ZED_Tracking_Viewer.dir/build
make[2]: Entering directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
[ 14%] Linking CXX executable "ZED Tracking Viewer"
/usr/bin/cmake -E cmake_link_script CMakeFiles/ZED_Tracking_Viewer.dir/link.txt --verbose=1
/usr/bin/c++      CMakeFiles/ZED_Tracking_Viewer.dir/src/CameraGL.o CMakeFiles/ZED_Tracking_Viewer.dir/src/PointCloud.o CMakeFiles/ZED_Tracking_Viewer.dir/src/Shader.o CMakeFiles/ZED_Tracking_Viewer.dir/src/Simple3DObject.o CMakeFiles/ZED_Tracking_Viewer.dir/src/Viewer.o CMakeFiles/ZED_Tracking_Viewer.dir/src/main.o  -o "ZED Tracking Viewer"  -L/usr/local/cuda/lib64  -L/usr/local/zed/lib  -L/usr/local/lib -rdynamic **/usr/local/zed/lib/libsl_zed.so /usr/local/zed/lib/libsl_depthcore.so /usr/local/zed/lib/libsl_calibration.so /usr/local/zed/lib/libsl_tracking.so /usr/local/zed/lib/libsl_disparityFusion.so /usr/local/zed/lib/libsl_svorw.so /usr/local/zed/lib/libcudpp.so /usr/local/zed/lib/libcudpp_hash.so** -lGLU -lGL -lglut -lXmu -lXi /usr/local/lib/libGLEW.so /usr/local/lib/libopencv_viz.so.3.1.0 /usr/local/lib/libopencv_videostab.so.3.1.0 /usr/local/lib/libopencv_superres.so.3.1.0 /usr/local/lib/libopencv_stitching.so.3.1.0 /usr/local/lib/libopencv_shape.so.3.1.0 /usr/local/lib/libopencv_photo.so.3.1.0 /usr/local/lib/libopencv_cudastereo.so.3.1.0 /usr/local/lib/libopencv_cudaoptflow.so.3.1.0 /usr/local/lib/libopencv_cudaobjdetect.so.3.1.0 /usr/local/lib/libopencv_cudalegacy.so.3.1.0 /usr/local/lib/libopencv_cudaimgproc.so.3.1.0 /usr/local/lib/libopencv_cudafeatures2d.so.3.1.0 /usr/local/lib/libopencv_cudacodec.so.3.1.0 /usr/local/lib/libopencv_cudabgsegm.so.3.1.0 /usr/local/lib/libopencv_calib3d.so.3.1.0 -lpthread -lX11 -lcuda /usr/local/cuda/lib64/libcudart.so /usr/local/cuda/lib64/libnppc.so /usr/local/cuda/lib64/libnppi.so /usr/local/cuda/lib64/libnpps.so /usr/local/zed/lib/libsl_zed.so /usr/local/zed/lib/libsl_depthcore.so /usr/local/zed/lib/libsl_calibration.so /usr/local/zed/lib/libsl_tracking.so /usr/local/zed/lib/libsl_disparityFusion.so /usr/local/zed/lib/libsl_svorw.so /usr/local/zed/lib/libcudpp.so /usr/local/zed/lib/libcudpp_hash.so -lGLU -lGL -lglut -lXmu -lXi /usr/local/lib/libGLEW.so -lpthread -lX11 -lcuda /usr/local/cuda/lib64/libcudart.so /usr/local/cuda/lib64/libnppc.so /usr/local/cuda/lib64/libnppi.so /usr/local/cuda/lib64/libnpps.so /usr/local/lib/libopencv_cudawarping.so.3.1.0 /usr/local/lib/libopencv_objdetect.so.3.1.0 /usr/local/lib/libopencv_cudafilters.so.3.1.0 /usr/local/lib/libopencv_cudaarithm.so.3.1.0 /usr/local/lib/libopencv_features2d.so.3.1.0 /usr/local/lib/libopencv_ml.so.3.1.0 /usr/local/lib/libopencv_highgui.so.3.1.0 /usr/local/lib/libopencv_videoio.so.3.1.0 /usr/local/lib/libopencv_imgcodecs.so.3.1.0 /usr/local/lib/libopencv_flann.so.3.1.0 /usr/local/lib/libopencv_video.so.3.1.0 /usr/local/lib/libopencv_imgproc.so.3.1.0 /usr/local/lib/libopencv_core.so.3.1.0 /usr/local/lib/libopencv_cudev.so.3.1.0 -Wl,-rpath,/usr/local/cuda/lib64:/usr/local/zed/lib:/usr/local/lib 
CMakeFiles/ZED_Tracking_Viewer.dir/src/main.o: In function `main':

**/home/vitob/git_repositories/zed-tracking-viewer/src/main.cpp:73: undefined reference to `sl::zed::Camera::Camera(std::string)'
/home/vitob/git_repositories/zed-tracking-viewer/src/main.cpp:103: undefined reference to `sl::zed::Camera::enableTracking(Eigen::Matrix<float, 4, 4, 0, 4, 4>&, bool, std::string)'
collect2: error: ld returned 1 exit status**

CMakeFiles/ZED_Tracking_Viewer.dir/build.make:291: recipe for target 'ZED Tracking Viewer' failed
make[2]: *** [ZED Tracking Viewer] Error 1
make[2]: Leaving directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ZED_Tracking_Viewer.dir/all' failed
make[1]: *** [CMakeFiles/ZED_Tracking_Viewer.dir/all] Error 2
make[1]: Leaving directory '/home/vitob/git_repositories/zed-tracking-viewer/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

As you can see the library are linked correctly. I installed the latest SDK v1.2. 

I checked related discussion (https://github.com/stereolabs/zed-ros-wrapper/issues/42), and I tried to have deleted /usr/local/zed and reinstalled SDK again, same issue here.

**Comment by oBraunPers** [comment]
Hi,

Did you try to delete the build directory , and restart the process : 
create "build" directory
cmake
make
?

Best,
OB.

**Comment by obraun-sl** [comment]
Hi,

Did you try to delete the build directory , and restart the process :
create "build" directory
cmake
make
?

Best,
OB.

**Comment by jinchenglee** [comment]
2008  rm -fr build/
 2009  cd bui
 2010  mkdir bui
 2011  rm -fr bui
 2012  mkdir build
 2013  ls
 2014  cd build/
 2015  cmake 
 2016  cmake ..
 2017  make VERBOSE=1
 2018  history |less
(END)

Just tried again. Same symptom. 

BTW, your default programs work fine. I mean ZED Depth Viewer, ZED Explorer etc.

**Comment by jinchenglee** [comment]
In case this helps. My gcc/g++ versions.

gcc (Ubuntu 4.9.4-2ubuntu1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (Ubuntu 4.9.4-2ubuntu1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jinchenglee** [comment]
Turns out to be gcc/g++ version issue. I changed to g++/gcc v6.2.0. Issue is gone. 

g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Scanning dependencies of target ZED_Tracking_Viewer
[ 14%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/CameraGL.o
[ 28%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/PointCloud.o
[ 42%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/Shader.o
[ 57%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/Simple3DObject.o
[ 71%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/Viewer.o
[ 85%] Building CXX object CMakeFiles/ZED_Tracking_Viewer.dir/src/main.o
[100%] Linking CXX executable "ZED Tracking V
